--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Catalyst-Serendipity/BountyPursuit
build-by-default: true
branches:
- main
projects:
  BountyPursuit:
    path: ""
    icon: "assets/icon.png"
...
