name: BountyPursuit
api: 5.3.0
version: 0.2.2
main: nicholass003\bounty\BountyPursuit
author: nicholass003
permissions:
  bountypursuit.command:
    default: true
  bountypursuit.command.list:
    default: true
  bountypursuit.command.remove:
    default: op
  bountypursuit.command.reward:
    default: true
  bountypursuit.command.target:
    default: true
  bountypursuit.command.top:
    default: op